sudo:
  false

language:
  php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
